version: '3.8'

services:
  app:
    image: node-server:latest
    environment:
      NODE_ENV: staging
      VIRTUAL_HOST: bytegum.localhost
    env_file:
      - ./.env
    ports:
      - "80:8000"
    restart: always