version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    image: devcloudappsacr.azurecr.io/dev/main:latest
    ports:
      - "8000-8400:8000"
    environment:
      - VIRTUAL_HOST=bytegum.localhost
      - NODE_ENV=room
    depends_on:
      - nginx-proxy
    networks:
      default:
        aliases:
          - bytegum.com
