name: run-tf-azure-script
author: Emmanuel Okafor
decription: A generic action to run terraform script

inputs:
  AZR_CLIENT_ID:
    required: true
  AZR_CLIENT_SECRET:
    required: true
  AZR_SUBSCRIPTION_ID:
    required: true
  AZR_TENANT_ID:
    required: true
  project:
    description: 'Entry project name'
    required: true
  key:
    description: 'Entry group name'
    required: true
  working-directory:
    description: 'Default working directory'
    default: 'tf'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Login Azure
      id: login
      run: az login --service-principal --username ${{secrets.AZR_CLIENT_ID}} --password ${{secrets.AZR_CLIENT_SECRET}} --tenant ${{secrets.AZR_TENANT_ID}}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Environment AZR: vm - ${{ env.prefix }}"
        mkdir -p _state
        terraform -chdir=terraform/azure/vm init \
          -backend-config="resource_group_name=${{ env.project }}-tfstate" \
          -backend-config="storage_account_name=${{ env.project }}storage" \
          -backend-config="container_name=${{ env.project }}tfstate" \
          -backend-config="key=${{ env.key }}-vm.terraform.tfstate" \
          -backend-config="subscription_id=${{ secrets.AZR_SUBSCRIPTION_ID }}" \
          -backend-config="tenant_id=${{ secrets.AZR_TENANT_ID }}" \
          -backend-config="client_id=${{ secrets.AZR_CLIENT_ID }}" \
          -backend-config="client_secret=${{ secrets.AZR_CLIENT_SECRET }}"