name: run-tf-azure-script
author: Emmanuel Okafor
decription: A generic action to run terraform script

inputs:
  envFile:
    description: 'Environment'
    required: true
  project:
    description: 'Entry project name'
    required: true
  key:
    description: 'Entry group name'
    required: true
    default: 'key'
  working-directory:
    description: 'Default working directory'
    default: 'tf'
  variable-path:
    description: 'The Path to variable'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ${{ inputs.envFile }}
        key: ${{ runner.os }}-file-${{ env.envFileName }}
        restore: true

    - name: Set up environment variables from file
      id: set-env
      shell: bash
      run: |
          while read line; do
            echo "$line" >> "$GITHUB_ENV"
          done < ${{ inputs.envFile }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Login Azure
      id: login
      shell: bash
      run: az login --service-principal --username ${{secrets.AZR_CLIENT_ID}} --password ${{secrets.AZR_CLIENT_SECRET}} --tenant ${{secrets.AZR_TENANT_ID}}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Execute Terraform Init : ${{ inputs.working-directory }} - ${{ env.prefix }} ${{ env.key }}"
        mkdir -p _state
        terraform init \
          -backend-config="${{ env.envFileName }}" \

#    - name: Terraform Plan
#      id: plan
#      working-directory: ${{ inputs.working-directory }}
#      run: |
#        echo "Execute Terraform Plan : ${{ inputs.working-directory }} - ${{ env.prefix }} ${{ env.key }}"
#        mkdir -p _state
#        terraform plan -no-color -input=false \
#          -var-file=${{ inputs.variable-path }} \
#          -out ./_state/${{ inputs.project }}.tfplan \
#          -lock=false
#      continue-on-error: false