name: run-tf-azure-script
author: Emmanuel Okafor
decription: A generic action to run terraform script

inputs:
  envName:
    description: 'Environment'
    required: true
    default: "env"

  envFile:
    description: 'Environment'
    required: true

  project:
    description: 'Entry project name'
    required: true
  key:
    description: 'Entry group name'
    required: true
    default: 'key'
  working-directory:
    description: 'Default working directory'
    default: 'tf'
  variable-path:
    description: 'The Path to variable'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Echo env
      shell: bash
      run: |
        ls -a
        cat ./${{ inputs.envFile }}

    - name: Set up environment variables from file
      id: set-env
      shell: bash
      run: source ${{ inputs.envFile }}

    - name: Echo Test Env Value
      id: debug-purpose
      shell: bash
      run: echo "Test Variable ${TEST}"
#
#    - name: Setup Terraform
#      uses: hashicorp/setup-terraform@v2
#
#    - name: Login Azure
#      id: login
#      shell: bash
#      run: az login --service-principal --username ${{env.AZR_CLIENT_ID}} --password ${{env.AZR_CLIENT_SECRET}} --tenant ${{env.AZR_TENANT_ID}}
#
#    - name: Terraform Init
#      id: init
#      working-directory: ${{ inputs.working-directory }}
#      shell: bash
#      run: |
#        echo "Execute Terraform Init : ${{ inputs.working-directory }} - ${{ env.prefix }} ${{ env.key }}"
#        mkdir -p _state
#        terraform init \
#          -backend-config="${{ inputs.env-file }}" \

#    - name: Terraform Plan
#      id: plan
#      working-directory: ${{ inputs.working-directory }}
#      run: |
#        echo "Execute Terraform Plan : ${{ inputs.working-directory }} - ${{ env.prefix }} ${{ env.key }}"
#        mkdir -p _state
#        terraform plan -no-color -input=false \
#          -var-file=${{ inputs.variable-path }} \
#          -out ./_state/${{ inputs.project }}.tfplan \
#          -lock=false
#      continue-on-error: false