version: '3.8'
services:
  app:
    image: ${IMAGE}
    command: ${COMMAND}
    volumes:
      - ./:/app
    environment:
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - "8000:8000"
    restart: always
    networks:
      - net

networks:
  net:
    external: true