version: '3.8'
services:
  app:
    image: ${IMAGE}
    volumes:
      - app-volume:/var/lib/app/content
    environment:
      NODE_ENV: ${NODE_ENV}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    env_file:
      - ./.env
    ports:
      - "8000-8400:8000"
    restart: always

volumes:
  app-volume:
    external: true

networks:
  default:
    external:
      name: nginx-proxy
