version: '3.8'
services:
  app:
    image: node-server:latest
    volumes:
      - app-volume:/var/lib/app/content
    environment:
      NODE_ENV: staging
      VIRTUAL_HOST: test.bytegum.com
    env_file:
      - ./.env
    ports:
      - 8000-8400:8000
    restart: always
    networks:
      - app-network
volumes:
  app-volume:
    external: true

networks:
  app-network:
      name: nginx-proxy
      external: true
