name: hello
author: Emmanuel Okafor
decription: A sample hello world git action

inputs:
  environment:
    description: 'Environment Name'
    required: true

runs:
  using: "composite"
  steps:
    - id: Testing
      run: echo "Hello World to ${{inputs.environment}}"
