name: AWS K8 Cloud Destroy

on:
  workflow_dispatch:
    inputs:
      TFAction:
        description: "Destroy Infrastructure"
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  configFile: "configs/aws-cloud.json"
  scriptPath: "terraform/aws"

jobs:
  envs:
    name: 'Set Envs'
    if: ${{ inputs.TFAction == true}}
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.variables.outputs.project }}
      bucket_region: ${{ steps.variables.outputs.bucket_region }}
      instance_type: ${{ steps.variables.outputs.instance_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set App Envs
        id: get-envs
        uses: ./.github/actions/set-aws-envs
        with:
          config-file: ${{ env.configFile }}

      - name: Set Outputs
        id: variables
        shell: bash
        run: |
          for VAR in $(compgen -e); do
            echo "${VAR,,}=${!VAR}" >> $GITHUB_OUTPUT
          done
  elb:
    name: 'EL Balancer'
    needs: [ envs ]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      bucket_region: ${{ needs.envs.outputs.bucket_region }}
      elbEnvFile: "elb.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert to json
        id: elbjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.elbEnvFile }}
          project: ${{ env.project }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.elbEnvFile }}
          path: ${{ env.elbEnvFile }}

      - name: Instantiate EL Balancer
        uses: ./.github/actions/tf-aws-destroy-script
        id: elb
        with:
          envFile: ${{ env.elbEnvFile }}
          project: ${{ env.project }}
          bucketRegion: ${{ env.bucket_region }}
          key: ${{ env.project }}-elb
          working-directory: ${{ env.scriptPath}}/elb
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        continue-on-error: false

  eks:
    name: 'EK Cluster'
    needs: [ envs, elb ]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      bucket_region: ${{ needs.envs.outputs.bucket_region }}
      eksEnvFile: "eks.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert to json
        id: eksjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.eksEnvFile }}
          project: ${{ env.project }}
          instance_type: ${{ env.instance_type }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.eksEnvFile }}
          path: ${{ env.eksEnvFile }}

      - name: Destroy EKS Cluster
        uses: ./.github/actions/tf-aws-destroy-script
        id: eks
        with:
          envFile: ${{ env.eksEnvFile }}
          project: ${{ env.project }}
          bucketRegion: ${{ env.bucket_region }}
          key: ${{ env.project }}-eks
          working-directory: ${{ env.scriptPath }}/eks
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        continue-on-error: false
