name: AZR VM CI

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  project: cloudstmdev
  location: centralus
  envFileName: "cloud.tfvars"

jobs:
  envs:
    name: 'Set Environments'
    runs-on: ubuntu-latest
    outputs:
      envFile: ${{ steps.cache-primes.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save Secret File secrets
        run: |
          echo "prefix = ${{ env.project }}" >> cloud.tfvars
          echo "location = ${{ env.location }}" >> cloud.tfvars
          cat ${{ env.envFileName }}
        shell: bash

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ env.envFileName }}

      - name: Cache file
        uses: actions/cache@v2
        with:
          clean: true
          path: ${{ env.envFileName }}
          key: file-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            file-${{ runner.os }}

  setup:
    name: 'Execute Cloud'
    needs: [envs]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Storage Account
        uses: ./.github/actions/create-azure-sa
        with:
          project: ${{ env.project }}
          location: ${{ env.location }}
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Create Resource Group
        uses: ./.github/actions/run-tf-azure-script
        with:
          project: ${{ env.project }}
          envFile: ${{ env.envFileName }}
          key: ${{ env.project }}-rg
          working-directory: "tf/azure/crg"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

