name: AZR DEPLOY VMS

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  project: acloudappsdev
  location: centralus
  configFile: "configs/cloud.json"

jobs:
  envs:
    name: 'Set Environments'
    runs-on: ubuntu-latest
    outputs:
      vm_names: ${{ steps.variables.outputs.vm_names }}
      api_names: ${{ steps.variables.outputs.api_names }}
      app_names: ${{ steps.variables.outputs.app_names }}
      api_suffixes: ${{ steps.variables.outputs.api_suffixes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set App Envs
        id: get-envs
        uses: ./.github/actions/set-envs
        with:
          configFile: ${{ env.configFile }}

      - name: Set Outputs
        id: variables
        shell: bash
        run: |
          echo "vm_names=${{ format('[{0}]', env.vm_names) }}" >> $GITHUB_OUTPUT
          echo "api_names=${{ format('[{0}]', env.api_names) }}" >> $GITHUB_OUTPUT
          echo "app_names=${{ env.app_names }}" >> $GITHUB_OUTPUT
          echo "api_suffixes=${{ env.api_suffixes }}" >> $GITHUB_OUTPUT

  sa:
    name: 'Storage Account'
    needs: [ envs ]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instantiate SA
        uses: ./.github/actions/create-azure-sa
        id: sa
        with:
          project: ${{ env.project }}
          location: ${{ env.location }}
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

  crg:
    name: 'Res Group & Registry'
    needs: [ sa ]
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      rg_location: ${{ steps.set-output.outputs.rg_location }}
      rg_name: ${{ steps.set-output.outputs.rg_name }}
    env:
      rgEnvFile: "rg.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cloud config
        id: rg-cloud-config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{ env.configFile }}
          prop_path: "resource-group"

      - name: convert to json
        id: rgjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.rgEnvFile }}
          prefix: ${{ env.project }}
          location: ${{ env.location }}
          prevent_resource_deletion:  ${{steps.rg-cloud-config.outputs.prevent_resource_deletion}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.rgEnvFile }}
          path: ${{ env.rgEnvFile }}

      - name: Instantiate RG & CR
        uses: ./.github/actions/tf-azure-script
        id: rg
        with:
          project: ${{ env.project }}
          envFile: ${{ env.rgEnvFile }}
          key: ${{ env.project }}-rg
          working-directory: "tf/azure/crg"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "rg_location=${{ env.rg_location }}" >> $GITHUB_OUTPUT
          echo "rg_name=${{ env.rg_name }}" >> $GITHUB_OUTPUT

  vn:
    name: 'Virtual Network'
    needs: [ crg ]
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      virtual_network_id: ${{ steps.set-output.outputs.virtual_network_id }}
      virtual_network_name: ${{ steps.set-output.outputs.virtual_network_name }}
      baston_dns: ${{ steps.set-output.outputs.baston_dns }}
      baston_id: ${{ steps.set-output.outputs.baston_id }}
    env:
      vnEnvFile: "vn.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert to json
        id: vmjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.vnEnvFile }}
          prefix: ${{ env.project }}
          location: ${{ needs.crg.outputs.rg_location }}
          group: ${{ needs.crg.outputs.rg_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.vnEnvFile }}
          path: ${{ env.vnEnvFile }}

      - name: Instantiate VNet
        uses: ./.github/actions/tf-azure-script
        id: vn
        with:
          project: ${{ env.project }}
          envFile: ${{ env.vnEnvFile }}
          key: ${{ env.project }}-vn
          working-directory: "tf/azure/vnet"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "virtual_network_id=${{ env.virtual_network_id }}" >> $GITHUB_OUTPUT
          echo "virtual_network_name=${{ env.virtual_network_name }}" >> $GITHUB_OUTPUT
          echo "baston_dns=${{ env.baston_dns }}" >> $GITHUB_OUTPUT
          echo "baston_id=${{ env.baston_id }}" >> $GITHUB_OUTPUT
  bst:
    name: 'Baston Host'
    needs: [ crg, vn ]
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      virtual_network_id: ${{ steps.set-output.outputs.virtual_network_id }}
      virtual_network_name: ${{ steps.set-output.outputs.virtual_network_name }}
      baston_dns: ${{ steps.set-output.outputs.baston_dns }}
      baston_id: ${{ steps.set-output.outputs.baston_id }}
    env:
      vnEnvFile: "vn.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert to json
        id: vmjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.vnEnvFile }}
          prefix: ${{ env.project }}
          location: ${{ needs.crg.outputs.rg_location }}
          group: ${{ needs.crg.outputs.rg_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.vnEnvFile }}
          path: ${{ env.vnEnvFile }}

      - name: Instantiate Baston
        uses: ./.github/actions/tf-azure-script
        id: vn
        with:
          project: ${{ env.project }}
          envFile: ${{ env.vnEnvFile }}
          key: ${{ env.project }}-bst
          working-directory: "tf/azure/bst"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "baston_dns=${{ env.baston_dns }}" >> $GITHUB_OUTPUT
          echo "baston_id=${{ env.baston_id }}" >> $GITHUB_OUTPUT
  vms:
    name: Virtual Machines ${{ matrix.items }}
    needs: [ envs, crg, vn ]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      vm: ${{ needs.envs.outputs.vm_names }}
      vmEnvFile: "vms-${{ matrix.items }}.tfvars"
    strategy:
      matrix:
        items: ${{ fromJSON(needs.envs.outputs.vm_names) }}
    outputs:
      vm_names: ${{ steps.set-output.outputs.vm_names }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cloud config
        id: vm-cloud-config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{ env.configFile }}
          prop_path: "virtual-machine"

      - name: Print VM Info
        id: vm-info
        run: |
          echo "vm name ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['name'] }}"
          echo "vm count ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['vmCount'] }}"

      - name: convert to json
        id: vmjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.vmEnvFile }}
          prefix: ${{ env.project }}
          group: ${{ needs.crg.outputs.rg_name }}
          name: ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['name'] }}
          vm_count: ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['vmCount'] }}
          admin_password: ${{ secrets.VM_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.vmEnvFile }}
          path: ${{ env.vmEnvFile }}

      - name: Instantiate VMachine(s)
        uses: ./.github/actions/tf-azure-script
        id: vm
        with:
          project: ${{ env.project }}
          envFile: ${{ env.vmEnvFile }}
          key: ${{ env.project }}-${{ matrix.items }}-vm
          working-directory: "tf/azure/vm"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "vm_names=${{ env.vm_names }}" >> $GITHUB_OUTPUT
  gw:
    name: Application Gateway
    needs: [ envs, crg, vms ]
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      gw_name: ${{ steps.set-output.outputs.gw_name }}
    env:
      app_names: ${{ needs.envs.outputs.app_names }}
      api_suffixes: ${{ needs.envs.outputs.api_suffixes }}
      vm: ${{ needs.envs.outputs.vm_names }}
      gwEnvFile: "gw.tfvars"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: convert to json
        id: gwjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.gwEnvFile }}
          prefix: ${{ env.project }}
          group: ${{ needs.crg.outputs.rg_name }}
          app_names: ${{ env.app_names }}
          api_suffixes: ${{ env.api_suffixes }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.gwEnvFile }}
          path: ${{ env.gwEnvFile }}

      - name: Initialize Gateway
        uses: ./.github/actions/tf-azure-script
        id: vm
        with:
          project: ${{ env.project }}
          envFile: ${{ env.gwEnvFile }}
          key: ${{ env.project }}-gw
          working-directory: "tf/azure/gw"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "gw_name=${{ env.gw_name }}" >> $GITHUB_OUTPUT

  gwc:
    name: Gateway Config ${{ matrix.items }}
    needs: [ envs, crg, gw ]
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      gw_name: ${{ steps.set-output.outputs.gw_name }}
    env:
      vm: ${{ needs.envs.outputs.vm_names }}
      gwcEnvFile: "gwc-${{ matrix.items }}.tfvars"
    strategy:
      matrix:
        items: ${{ fromJSON(needs.envs.outputs.vm_names) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cloud config
        id: vm-cloud-config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{ env.configFile }}
          prop_path: "virtual-machine"

      - name: convert to json
        id: gwcjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.gwcEnvFile }}
          prefix: ${{ env.project }}
          group: ${{ needs.crg.outputs.rg_name }}
          name: ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['name'] }}
          vm_count: ${{ fromJson(steps.vm-cloud-config.outputs.vms)[matrix.items]['vmCount'] }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.gwcEnvFile }}
          path: ${{ env.gwcEnvFile }}

      - name: Configure Gateway
        uses: ./.github/actions/tf-azure-script
        id: vm
        with:
          project: ${{ env.project }}
          envFile: ${{ env.gwcEnvFile }}
          key: ${{ env.project }}-${{ matrix.items }}-gwc
          working-directory: "tf/azure/gwc"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "gw_name=${{ env.gw_name }}" >> $GITHUB_OUTPUT
          echo "backend_pool_name=${{ env.backend_pool_name }}" >> $GITHUB_OUTPUT
  apim:
    name: Api Management Service
    needs: [ envs, crg, vn ]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      apimEnvFile: "apim.tfvars"
    outputs:
      apim_id: ${{ steps.set-output.outputs.apim_id }}
      gateway_url: ${{ steps.set-output.outputs.gateway_url }}
      portal_url: ${{ steps.set-output.outputs.portal_url }}
      developer_portal_url: ${{ steps.set-output.outputs.developer_portal_url }}
      management_api_url: ${{ steps.set-output.outputs.management_api_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cloud config
        id: apim-cloud-config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{ env.configFile }}
          prop_path: "api-management"

      - name: convert to json
        id: apimjson
        uses: schdck/create-env-json@v1
        with:
          file-name: ${{ env.apimEnvFile }}
          prefix: ${{ env.project }}
          group: ${{ needs.crg.outputs.rg_name }}
          environment: ${{ needs.envs.outputs.environment }}
          capacity: ${{steps.apim-cloud-config.outputs.capacity }}
          sku: ${{steps.apim-cloud-config.outputs.sku }}
          publisher_name: ${{steps.apim-cloud-config.outputs.publisher_name }}
          publisher_email: ${{steps.apim-cloud-config.outputs.publisher_email}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.apimEnvFile }}
          path: ${{ env.apimEnvFile }}

      - name: Instantiate API Magt Services
        uses: ./.github/actions/tf-azure-script
        id: apim
        with:
          project: ${{ env.project }}
          envFile: ${{ env.apimEnvFile }}
          key: ${{ env.project }}-apim
          working-directory: "tf/azure/apim"
          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
        continue-on-error: false

      - name: Set output
        id: set-output
        run: |
          echo "apim_id=${{ env.apim_id }}" >> $GITHUB_OUTPUT
          echo "gateway_url=${{ env.gateway_url }}" >> $GITHUB_OUTPUT
          echo "management_api_url=${{ env.management_api_url }}" >> $GITHUB_OUTPUT
          echo "portal_url=${{ env.portal_url }}" >> $GITHUB_OUTPUT
          echo "developer_portal_url=${{ env.developer_portal_url }}" >> $GITHUB_OUTPUT


#  apimp:
#    name: Api Services ${{ matrix.items }}
#    needs: [ envs, crg, apim ]
#    permissions: write-all
#    runs-on: ubuntu-latest
#    env:
#      api_names: ${{ needs.envs.outputs.api_names }}
#      apimpEnvFile: "apimp-${{ matrix.items }}.tfvars"
#    outputs:
#      apim_id: ${{ steps.set-output.outputs.apim_id }}
#    strategy:
#      matrix:
#        items: ${{ fromJSON(needs.envs.outputs.api_names) }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Get cloud config
#        id: apimp-cloud-config
#        uses: ActionsTools/read-json-action@main
#        with:
#          file_path: ${{ env.configFile }}
#          prop_path: "api-management"
#
#      - name: Print VM Info
#        id: vm-info
#        run: |
#          echo "publisher name ${{ steps.apimp-cloud-config.outputs.publisher_name }}"
#          echo "publisher email ${{ steps.apimp-cloud-config.outputs.publisher_email }}"
#          echo "publisher api ${{ fromJson(steps.apimp-cloud-config.outputs.apis)[matrix.items]['name'] }}"
#
#      - name: convert to json
#        id: apimpjson
#        uses: schdck/create-env-json@v1
#        with:
#          file-name: ${{ env.apimpEnvFile }}
#          prefix: ${{ env.project }}
#          group: ${{ needs.crg.outputs.rg_name }}
#          name: ${{ matrix.items }}
#          display_name: ${{ fromJson(steps.apimp-cloud-config.outputs.apis)[matrix.items]['name'] }}
#          suffix: ${{ fromJson(steps.apimp-cloud-config.outputs.apis)[matrix.items]['suffix'] }}
#          endpoints: ${{ fromJson(steps.apimp-cloud-config.outputs.apis)[matrix.items]['endpoints'] }}
#          header: ${{ fromJson(steps.apimp-cloud-config.outputs.apis)[matrix.items]['header'] }}
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ env.apimpEnvFile }}
#          path: ${{ env.apimpEnvFile }}
#
#      - name: Api Setups
#        uses: ./.github/actions/tf-azure-script
#        id: apim
#        with:
#          project: ${{ env.project }}
#          envFile: ${{ env.apimpEnvFile }}
#          key: ${{ env.project }}-${{ matrix.items }}-apimp
#          working-directory: "tf/azure/apimp"
#          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
#          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
#          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
#          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
#        continue-on-error: false
#
#      - name: Set output
#        id: set-output
#        run: |
#          echo "api_management_api_name=${{ env.api_management_api_name }}" >> $GITHUB_OUTPUT
#          echo "api_management_api_id=${{ env.api_management_api_id }}" >> $GITHUB_OUTPUT