name: AZR VM CI

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: ["AZR VM Cloud"]
    types:
      - completed
  workflow_call:
    secrets:
      AZR_CLIENT_ID:
        description: 'Azure client id'
        required: true
      AZR_CLIENT_SECRET:
        description: 'Azure secret key'
        required: true
      AZR_TENANT_ID:
        description: 'Azure tenant id'
        required: true
      AZR_SUBSCRIPTION_ID:
        description: 'Azure subscription id'
        required: true
      AZURE_VM_APP_SECRET:
        description: 'Azure vm secret'
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      HAS_VM:
        description: "If a virtual machine already exist"
        value: ${{ jobs.setups.outputs.HAS_VM }}
    inputs:
      TFAction:
        type: boolean
        default: false
      is_workflow:
        required: true
        type: boolean
        default: false
      project:
        required: true
        type: string
      repository:
        required: true
        type: string
      service:
        required: true
        type: string
      hostname-format:
        required: true
        type: string
      port:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  current_project: cloudstgdev
  current_service: quest
  current_port: 8000:8000
  current_hostname_format: "stm-{0}.stemulidev.com"
  image-name: stm-quest
  dockerfile: './app/Dockerfile'
  startCommand: yarn start
  location: 'centralus'
  environment: 'stg'
  appSecret: ${{ secrets.AWS_K8_APP_SECRET }}

jobs:
  envs:
    if: ${{ inputs.TFAction == false && github.event.workflow_run.conclusion == 'success' || inputs.is_workflow == true || github.event_name == 'push' }}
    name: 'Validate Env Variables'
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.variables.outputs.project }}
      service: ${{ steps.variables.outputs.service }}
      port: ${{ steps.variables.outputs.port }}
      hostname-format: ${{ steps.variables.outputs.hostname-format }}
      dockerfile: ${{ steps.variables.outputs.dockerfile }}
    steps:
      - name: Initialize environments
        run: |
          EP="${{inputs.project}}"
          ES="${{inputs.service}}"
          PRT="${{inputs.port}}"
          HOST_FMT="${{inputs.hostname-format}}"
          ENV_HOST_FMT="${{env.current_hostname_format}}"
          DOCFILE="${{ inputs.dockerfile }}"

          PROJECT="${EP:-${{env.current_project}}}"
          SERVICE="${ES:-${{env.current_service}}}"
          PORT="${PRT:-${{env.current_port}}}"
          
          HOST_FORMAT="${HOST_FMT:-$ENV_HOST_FMT}"
          DOCKER_FILE="${DOCFILE:-${{ env.dockerfile }}}"

          echo "project=${PROJECT}" >> "$GITHUB_ENV"
          echo "service=${SERVICE}" >> "$GITHUB_ENV"
          echo "port=${PORT}" >> "$GITHUB_ENV"
          echo "hostname-format=${HOST_FORMAT}" >> "$GITHUB_ENV"
          echo "dockerfile=${DOCKER_FILE}" >> "$GITHUB_ENV"
      - name: Set Env
        id: variables
        run: |
          echo "project=${{ env.project }}" >> $GITHUB_OUTPUT
          echo "service=${{ env.service }}" >> $GITHUB_OUTPUT
          echo "port=${{ env.port }}" >> $GITHUB_OUTPUT
          echo "hostname-format=${{env.hostname-format}}" >> $GITHUB_OUTPUT
          echo "dockerfile=${{ env.dockerfile }}" >> $GITHUB_OUTPUT

  config:
    name: 'Setup Config Variables'
    needs: [envs]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      service: ${{ needs.envs.outputs.service }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      dockerfile: ${{ needs.envs.outputs.dockerfile }}
    outputs:
      hostname:       ${{ steps.resolved.outputs.hostname }}
      git-sha:        ${{ steps.resolved.outputs.git-sha }}
      docker-tag:     ${{ steps.resolved.outputs.docker-tag }}
      isPr:           ${{ steps.PR.outputs.pr_found }}
    steps:
      - id: debug-context
        run: |
          echo "event_name      ${{ github.event_name }}"
          echo "project        ${{ env.project }}"
          echo "hostname-format    ${{ env.hostname-format }}"

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: "Pull Request ${{ steps.PR.outputs.number }}"
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo "Source branch ${{ fromJSON(steps.PR.outputs.pr).head.ref }}"
          echo "Destination branch ${{ fromJSON(steps.PR.outputs.pr).base.ref }}"

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Slugify Value
        uses: rlespinasse/slugify-value@v1.4.0
        with:
          slug-maxlength: 30
          key: feat-name
          value: ${{ steps.branch-name.outputs.current_branch }}

      - name: Set variables
        id: variables
        run: |
          echo "hostname=${{ format(env.hostname-format, env.FEAT-NAME_SLUG_URL) }}" >> $GITHUB_ENV
          echo "docker-tag=${{ env.FEAT-NAME_SLUG_URL }}" >> $GITHUB_ENV
          echo "git-sha=${{ steps.commit.outputs.short }}" >> $GITHUB_ENV

      - name: Resolve outputs
        id: resolved
        run: |
          echo "git-sha=${{ env.git-sha }}" >> $GITHUB_OUTPUT
          echo "hostname=${{ env.hostname }}" >> $GITHUB_OUTPUT
          echo "docker-tag=${{ env.docker-tag }}" >> $GITHUB_OUTPUT
          echo "git-sha      ${{ env.git-sha }}"
          echo "hostname      ${{ env.hostname }}"
          echo "docker-tag      ${{ env.docker-tag }}"
          echo "event_name      ${{ github.event_name }}"

  deploy-image:
    name: 'Push Image to Cloud Registry'
    needs: [envs, config]
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      service: ${{ needs.envs.outputs.service }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      dockerfile: ${{ needs.envs.outputs.dockerfile }}
    steps:
      - name: --- For debugging ---
        id: debug-context
        run: |
          echo "event_name      ${{ github.event_name }}"
          echo "hostname        ${{ needs.config.outputs.hostname }}"
          echo "docker-tag      ${{ needs.config.outputs.docker-tag }}"
          echo "project         ${{ env.project }}"

      - name: Checkout
        uses: actions/checkout@v3
      - name: Login Azure
        id: login
        run: |
          az login --service-principal --username ${{secrets.AZR_CLIENT_ID}} --password ${{secrets.AZR_CLIENT_SECRET}} --tenant ${{secrets.AZR_TENANT_ID}}
          az acr login --name "${{env.project}}acr.azurecr.io"
      - name: Decode Secret
        if: ${{ env.appSecret }}
        run: DECODED=$(echo ${{ secrets.AZR_VM_APP_SECRET }} | base64 --decode > vm/.env)
      - name: Update Docker Compose File
        env:
          IMAGE: ${{ env.project }}acr.azurecr.io/${{ env.service }}/${{ env.image-name }}:${{ needs.config.outputs.docker-tag }}
          COMMAND: ${{ env.startCommand }}
          VIRTUAL_HOST: ${{ needs.config.outputs.hostname }}
          NODE_ENV: ${{ env.environment }}
        run: |
          cat ./app/docker-compose.yml | envsubst > ./vm/docker-compose.yml
          ls
          cat ./vm/docker-compose.yml
          cat ./vm/.env
      - name: Push File to
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.project }}-dns.${{ env.location }}.cloudapp.azure.com
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          rm: true
          source: "vm/."
          target: "app"
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          file: ${{ env.dockerfile }}
          tags: ${{env.project}}acr.azurecr.io/${{ env.service }}/${{ env.image-name }}:${{ needs.config.outputs.docker-tag }}

      - name: Cleanups
        run: |
          FILE=./env
          if [ -f "$FILE" ]; then
            echo secret file removed
             rm -r env
          fi

  deploy:
    name: 'Deploy Image to Container in VM'
    needs: [ envs, config, deploy-image ]
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      service: ${{ needs.envs.outputs.service }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      dockerfile: ${{ needs.envs.outputs.dockerfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Repo to Artifact
        if: ${{ inputs.is_workflow == true }}
        uses: actions/download-artifact@master
        with:
          name: cloud-scripts
          path: ${{ inputs.repository }}
      - name: Copy Script files to context
        if: ${{ inputs.is_workflow == true }}
        run: |
          ls
          cp -a "${{ inputs.repository }}/." ./
          rm -r "${{ inputs.repository }}"
          ls -a
      - name: Login Azure
        id: login
        run: |
          az login --service-principal --username ${{secrets.AZR_CLIENT_ID}} --password ${{secrets.AZR_CLIENT_SECRET}} --tenant ${{secrets.AZR_TENANT_ID}}

      - name: Deploy latest image
        id: deploy
        run: |
          echo "Spin/Update container with latest image"
          az vm run-command invoke \
            -g ${{env.project}}-group \
            -n ${{env.project}}-vm \
            --command-id RunShellScript \
            --scripts 'sudo chmod +x ./app/vm/deploy.sh && sudo ./app/vm/deploy.sh'
          echo "Successfully Deployed to ${{ needs.config.outputs.hostname }}"