name: AZR VM CI

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  project: cloudstmdev
  location: centralus

  envFileName: "cloud.tfvars"
  envFilePath: "."

jobs:
  envs:
    name: 'Set Environments'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save Secret File secrets
        run: |
          echo "TEST=HELLO" >> cloud.tfvars
          echo "AZR_SUBSCRIPTION_ID=${{secrets.AZR_SUBSCRIPTION_ID}}" >> ${{ env.envFilePath }}/${{ env.envFile }}
          echo "AZR_TENANT_ID=${{secrets.AZR_TENANT_ID}}" >> ${{ env.envFilePath }}/${{ env.envFile }}
          echo "AZR_CLIENT_ID=${{secrets.AZR_CLIENT_ID}}" >> ${{ env.envFilePath }}/${{ env.envFile }}
          echo "AZR_CLIENT_SECRET=${{secrets.AZR_CLIENT_SECRET}}" >> ${{ env.envFilePath }}/${{ env.envFile }}
          cat ${{ env.envFilePath }}/${{ env.envFile }}
        shell: bash

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ env.envFilePath }}/${{ env.envFile }}

      - name: Upload environment file to Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.envFileName }}
          path: ${{ env.envFilePath }}

  setup:
    name: 'Execute Cloud'
    needs: [envs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Repo to Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ env.envFileName }}
          path: ${{ env.envFilePath }}

      - name: Echo env
        shell: bash
        run: cat ${{ env.envFilePath }}/${{ env.envFile }}


      - name: Init Storage Account
        uses: ./.github/actions/run-tf-azure-script
        with:
          project: ${{ env.project }}
          location: ${{ env.location }}
          envFile: ${{ env.envFile }}
#
#      - name: Create Resource Group
#        uses: ./.github/actions/run-tf-azure-script
#        with:
#          project: ${{ env.project }}
#          key: ${{ env.project }}-rg
#          working-directory: "tf/azure/crg"
#          AZR_CLIENT_ID: ${{secrets.AZR_CLIENT_ID}}
#          AZR_CLIENT_SECRET: ${{secrets.AZR_CLIENT_SECRET}}
#          AZR_SUBSCRIPTION_ID: ${{secrets.AZR_SUBSCRIPTION_ID}}
#          AZR_TENANT_ID: ${{secrets.AZR_TENANT_ID}}
