name: Build App

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      buildCommand:
        type: string
        default: "npm run build --if-present"
      unitTestCommand:
        type: string
      e2eTestCommand:
        type: string
jobs:
  build-ci:
    name: "Build CI"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: ${{ inputs.buildCommand }}
      - name: Run Unit Test
        if: ${{ inputs.unitTestCommand }}
        run: ${{ inputs.unitTestCommand }}

      - name: Run e2e Test
        if: ${{ inputs.e2eTestCommand }}
        run: ${{ inputs.e2eTestCommand }}

  docker:
    name: 'Docker build'
    runs-on: ubuntu-latest
    needs: [ build-ci ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: docker build -t ${{ inputs.project }}-api -f ${{ inputs.dockerfile }} ./