name: CI

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: [ "Infrastructure" ]
    types:
      - completed
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      HAS_VM:
        description: "If a virtual machine already exist"
        value: ${{ jobs.setups.outputs.HAS_VM }}
    inputs:
      is_workflow:
        required: true
        type: boolean
        default: false
      project:
        required: true
        type: string
      repository:
        required: true
        type: string
      service:
        required: true
        type: string
      hostname-format:
        required: true
        type: string
      port:
        required: true
        type: string
      docker-context:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  current_project: localstgops
  current_port: 8080
  current_hostname_format: "pr-{0}.voomsway.com"
  namespace: stg
  image-name: stmx
  hostname: 'voomsway'
  docker-context: './app'

jobs:
  envs:
    if: ${{ inputs.TFAction == false && (github.event.workflow_run.conclusion == 'success' || inputs.is_workflow == false) }}
    name: 'Validate Env Variables'
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.variables.outputs.project }}
      port: ${{ steps.variables.outputs.port }}
      hostname-format: ${{ steps.variables.outputs.hostname-format }}
      docker-context: ${{ steps.variables.outputs.docker-context }}
    steps:
      - name: Initialize environments
        run: |
          EP="${{inputs.project}}"
          PRT="${{inputs.port}}"
          HOST_FMT="${{inputs.hostname-format}}"
          ENV_HOST_FMT="${{env.current_hostname_format}}"
          DOCTX="${{ inputs.docker-context }}"

          PROJECT="${EP:-${{env.current_project}}}"
          PORT="${PRT:-${{env.current_port}}}"
          
          HOST_FORMAT="${HOST_FMT:-$ENV_HOST_FMT}"
          DOCKER_CONTEXT="${DOCTX:-${{ env.docker-context }}}"

          echo "project=${PROJECT}" >> "$GITHUB_ENV"
          echo "port=${PORT}" >> "$GITHUB_ENV"
          echo "hostname-format=${HOST_FORMAT}" >> "$GITHUB_ENV"
          echo "docker-context=${DOCKER_CONTEXT}" >> "$GITHUB_ENV"
      - name: Set Env
        id: variables
        run: |
          echo "project=${{ env.project }}" >> $GITHUB_OUTPUT
          echo "port=${{ env.port }}" >> $GITHUB_OUTPUT
          echo "hostname-format=${{env.hostname-format}}" >> $GITHUB_OUTPUT
          echo "docker-context=${{ env.docker-context }}" >> $GITHUB_OUTPUT

  config:
    if: ${{ inputs.TFAction == false && (github.event.workflow_run.conclusion == 'success' || inputs.is_workflow == false) }}
    name: 'Setup Config Variables'
    needs: [envs]
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      docker-context: ${{ needs.envs.outputs.docker-context }}
    outputs:
      hostname:       ${{ steps.resolved.outputs.hostname }}
      git-sha:        ${{ steps.resolved.outputs.git-sha }}
      docker-tag:     ${{ steps.resolved.outputs.docker-tag }}
      isPr:           ${{ steps.PR.outputs.pr_found }}
    steps:
      - id: debug-context
        run: |
          echo "event_name      ${{ github.event_name }}"
          echo "project        ${{ env.project }}"
          echo "hostname-format    ${{ env.hostname-format }}"

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: "Pull Request ${{ steps.PR.outputs.number }}"
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo "Source branch ${{ fromJSON(steps.PR.outputs.pr).head.ref }}"
          echo "Destination branch ${{ fromJSON(steps.PR.outputs.pr).base.ref }}"

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Slugify Value
        uses: rlespinasse/slugify-value@v1.4.0
        with:
          slug-maxlength: 30
          key: feat-name
          value: ${{ steps.branch-name.outputs.current_branch }}

      - name: Set variables
        id: variables
        run: |
          echo "hostname=${{ format(env.hostname-format, env.FEAT-NAME_SLUG_URL) }}" >> $GITHUB_ENV
          echo "docker-tag=${{ env.FEAT-NAME_SLUG_URL }}" >> $GITHUB_ENV
          echo "git-sha=${{ steps.commit.outputs.short }}" >> $GITHUB_ENV

      - name: Resolve outputs
        id: resolved
        run: |
          echo "git-sha=${{ env.git-sha }}" >> $GITHUB_OUTPUT
          echo "hostname=${{ env.hostname }}" >> $GITHUB_OUTPUT
          echo "docker-tag=${{ env.docker-tag }}" >> $GITHUB_OUTPUT
          echo "git-sha      ${{ env.git-sha }}"
          echo "hostname      ${{ env.hostname }}"
          echo "docker-tag      ${{ env.docker-tag }}"
          echo "event_name      ${{ github.event_name }}"

  push-image:
    if: ${{ inputs.TFAction == false && (github.event.workflow_run.conclusion == 'success' || inputs.is_workflow == false) }}
    name: 'Push Image to Cloud Registry'
    needs: [envs, config]
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      docker-context: ${{ needs.envs.outputs.docker-context }}
    steps:
      - name: --- For debugging ---
        id: debug-context
        run: |
          echo "event_name      ${{ github.event_name }}"
          echo "hostname        ${{ needs.config.outputs.hostname }}"
          echo "docker-tag      ${{ needs.config.outputs.docker-tag }}"
          echo "project         ${{ env.project }}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ env.docker-context }}
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.project }}:${{ needs.config.outputs.docker-tag }}

  deploy:
    if: ${{ inputs.TFAction == false && (github.event.workflow_run.conclusion == 'success' || inputs.is_workflow == false) }}
    needs: [ envs, push-image, config ]
    name: 'deploy to AWS EKS'
    runs-on: ubuntu-latest
    env:
      project: ${{ needs.envs.outputs.project }}
      port: ${{ needs.envs.outputs.port }}
      hostname-format: ${{ needs.envs.outputs.hostname-format }}
      docker-context: ${{ needs.envs.outputs.docker-context }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update kubernetes config
        run: |
          echo "aws eks update-kubeconfig --name ${{ env.project }}-k8-cluster --region ${{ secrets.AWS_REGION }}"
          aws eks update-kubeconfig --name ${{ env.project }}-k8-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy image to kubernetes cluster
        env:
          APP_NAME:  ${{ env.project }}
          IMAGE_TAG: ${{ needs.config.outputs.docker-tag }}
          NAMESPACE: ${{ env.namespace }}
          INGRESS_HOSTNAME: ${{ env.hostname }}
          REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ env.project }}
          PORT: ${{ env.current_port }}
        run: |
          cat ./_kubernetes/service.yml | envsubst | kubectl apply -f -
          cat ./_kubernetes/deployment.yml | envsubst | kubectl apply -f -
          cat ./_kubernetes/ingress.yml | envsubst | kubectl apply -f -

      - name: Restart Pods
        id: restart-pods
        run: kubectl rollout restart deployment ${{ env.image-name }}-dpl --namespace=${{ env.namespace }}
        continue-on-error: true # will fail on first deploy

      - name: Cleanups
        run: |
          rm -r /home/runner/.kube/config